name: Execute Tests, Publish Docker version, Deploy App, Smoke Test

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

on:
  push:
    branches:
      - main
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn spring-boot:build-image -DskipTests --file pom.xml -e -X -Dspring-boot.build-image.imageName=dockerfile:${{ env.VERSION }}

      - name: Login to DockerHub
        run: docker login
          -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
      
      - name: Generate Docker tag
        run: docker tag dockerfile:${{ env.VERSION }} ${{ env.DOCKER_USERNAME }}/scrum-web:${{ env.VERSION }}
        
      - name: Push image to DockerHub
        run: docker push ${{ env.DOCKER_USERNAME }}/scrum-web:${{ env.VERSION }}